apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-database
  template:
    metadata:
      labels:
        app: todo-database
    spec:
      containers:
        - name: mongo
          image: mongo:6
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongo-storage
      volumes:
        - name: mongo-storage
          emptyDir: {} # You can replace this with a persistent volume later

---
apiVersion: v1
kind: Service
metadata:
  name: todo-database
spec:
  type: ClusterIP
  ports:
    - port: 27017
  selector:
    app: todo-database
